### ISSUE TITLE
node 12がサポート切れしている

### ISSUE THREAD

**Issue by nmatsui** [Personal-Data-Linkage-Module/pxr-catalog-service#2]
# 現在の状況
dockerコンテナのベースイメージとして`node:12`が使われているが、node.js 12系は2022/04/30に保守期限が切れており、セキュリティ上問題がある。
https://github.com/Personal-Data-Linkage-Module/pxr-catalog-service/blob/2619bbb33de3729b26c26dee91524e5c672c83b4/Dockerfile#L5
```
~$ docker run -it node:12 /bin/bash
root@e8da11beb712:/# node -v
v12.22.12
```

# 修正内容
* ベースイメージをサポート中のLTSであるnode.js 18系以降に変更し、依存ライブラリ等も合わせて更新して動作確認を行う

**Comment by smit-akiyama** [comment]
Node.js 18に対応したコードをdevelopブランチにマージしました。
本件はクローズいたします。
